### ISSUE TITLE
docker run , upload txt response 500

### ISSUE THREAD

**Issue by MSYXing** [guangzhengli/ChatFiles#101]
http://149.28.49.175:3000/api/embedding
        
        POST http://149.28.49.175:3000/api/embedding 500 (Internal Server Error)
p @ index-4eacaeeb93b9ac51.js:1
(匿名) @ index-4eacaeeb93b9ac51.js:1
Promise.then(异步)
x @ index-4eacaeeb93b9ac51.js:1
c @ index-4eacaeeb93b9ac51.js:1
onChange @ index-4eacaeeb93b9ac51.js:1
eU @ framework-73b8966a3c579ab0.js:9
eH @ framework-73b8966a3c579ab0.js:9
(匿名) @ framework-73b8966a3c579ab0.js:9
re @ framework-73b8966a3c579ab0.js:9
rn @ framework-73b8966a3c579ab0.js:9
(匿名) @ framework-73b8966a3c579ab0.js:9
oP @ framework-73b8966a3c579ab0.js:9
eF @ framework-73b8966a3c579ab0.js:9
ro @ framework-73b8966a3c579ab0.js:9
nU @ framework-73b8966a3c579ab0.js:9
nD @ framework-73b8966a3c579ab0.js:9
index-4eacaeeb93b9ac51.js:1 save embedding failed:  Internal Server Error
react_devtools_backend_compact.js:2367  Error: save embedding failed: ' Internal Server Error
    at index-4eacaeeb93b9ac51.js:1:13464
    at async p (index-4eacaeeb93b9ac51.js:1:12712)
    at async index-4eacaeeb93b9ac51.js:1:12615
    at async x (index-4eacaeeb93b9ac51.js:1:12381)
    at async c (index-4eacaeeb93b9ac51.js:1:11711)
overrideMethod @ react_devtools

**Comment by guangzhengli** [comment]
Please provide more detail exception stack.
