### ISSUE TITLE
Each user is assigned a limited credit to access the OpenAI service

### ISSUE THREAD

**Issue by anhhtca** [guangzhengli/ChatFiles#104]
Is there a way to implement the following idea: each user is assigned a limited credit to access the OpenAI service in the event that they do not have or choose not to provide their own API key?

Imagine that our website only offers a few data analysis functions without including Open AI. Users will use their own API keys or can try a trial usage with our $1-2 offer.

Thanks in advanced.

**Comment by guangzhengli** [comment]
The current project is just an open-source project, and there is currently no plan to support this feature.
