### ISSUE TITLE
File: Error: `html2text` is required to parse Epub files: `pip install html2text`

### ISSUE THREAD

**Issue by shenfu1991** [guangzhengli/ChatFiles#11]
Uploading an epub format e-book to the webpage results in an error message at the file name: File: Error: `html2text` is required to parse Epub files: `pip install html2text`. After installing pip install html2text, the same error still occurs."

**Comment by InitialXKO** [comment]
It should be one line missing in requirements.txt.

**Comment by guangzhengli** [comment]
html2text is already in requirements.txt, you can redownload the latest image to resolve this issue.
