### ISSUE TITLE
locally run failed

### ISSUE THREAD

**Issue by michael7908** [guangzhengli/ChatFiles#12]
File: Error: The constructor now takes in a list of Node objects. Since you are passing in a list of Document objects, please use `from_documents` instead. 

after I uploaded a PDF file,I got this. any help? thanks!

**Comment by guangzhengli** [comment]
May I ask what type of file you are uploading? pdf? or epub?

**Comment by michael7908** [comment]
PDF发自我的 iPhone在 2023年4月7日，14:19，guangzhengli ***@***.***> 写道：﻿
May I ask what type of file you are uploading? pdf? or epub?

**Comment by guangzhengli** [comment]
At present, I don't reproduce this issue locally. The error was caused by the llama_index create index function. I upgraded llama_index to the latest version and modified the from_documents method. Please test whether pulling the image again is successful. Thank you, and best wishes.

**Comment by CodeBot-del** [comment]
> File: Error: The constructor now takes in a list of Node objects. Since you are passing in a list of Document objects, please use `from_documents` instead.
> 
> after I uploaded a PDF file,I got this. any help? thanks!

Add from_documents after passing your vector index classifier, for example;
change this:-
index = GPTSimpleVectorIndex(documents)

adding from_documents, it will be:-
index = GPTSimpleVectorIndex.from_documents(documents)

I suppose it will work just fine.

**Comment by guangzhengli** [comment]
It seems your OpenAI key is incorrect, do you set the env with OPENAI_API_KEY=sk-xxxx ?

**Comment by Ilya88Weber** [comment]
> It seems your OpenAI key is incorrect, do you set the env with OPENAI_API_KEY=sk-xxxx ?

thanks. I clear browser cash and set os.environ['OPENAI_API_KEY'] = 
problem fixed!

**Comment by AkhileshNegi** [comment]
Hey @guangzhengli @Ilya88Weber I faced the same issue mentioned at the top of the issue by @michael7908  where

`File: Error: The constructor now takes in a list of Node objects. Since you are passing in a list of Document objects, please use from_documents instead.`

I resolved that, Thanks to this thread. 

However, I am getting this error now 
`ImportError: tiktoken package not found, please run `pip install tiktoken`
Can someone please help
