### ISSUE TITLE
Im gettin an error after running "npm run dev" in the shell: TypeError: Cannot read properties of undefined (reading 'indexName')

### ISSUE THREAD

**Issue by rezteknoloji** [guangzhengli/ChatFiles#120]
Hi,
I tried the program but got issue:  **TypeError: Cannot read properties of undefined (reading 'indexName')** even though its defined,
![image](https://github.com/guangzhengli/ChatFiles/assets/105365728/696129cf-12bf-44ac-98f0-24f8f9b6b939)

The error
![image](https://github.com/guangzhengli/ChatFiles/assets/105365728/694a3185-c868-4d88-8a15-f1ebb5759e3f)

Thank you :)

**Comment by wenwenc9** [comment]
Excuse me, I see you have closed this issue. How did you solve it?

**Comment by wenwenc9** [comment]
> 

Excuse me, I see you have closed this issue. How did you solve it?
