### ISSUE TITLE
上传文件提示 Node objects 和 Document objects 报错

### ISSUE THREAD

**Issue by zarswow** [guangzhengli/ChatFiles#13]
![image](https://user-images.githubusercontent.com/103822120/230533617-6e26ff66-1a3d-4d48-a5ee-d66d703cee3b.png)

在按照 requirements.txt 里的要求安装完依赖环境之后，上传文件就会提示：

> File: Error: The constructor now takes in a list of Node objects. Since you are passing in a list of Document objects, please use `from_documents` instead.

不知道该怎么解决，辛苦您帮我看一下是不是我哪里做错了。

**Comment by guangzhengli** [comment]
请问您上传的文件是什么类型的？

**Comment by zarswow** [comment]
上传测试了 pdf、txt 和 epub，都是相同的报错

**Comment by guangzhengli** [comment]
目前还没有在本地复现这个问题，错误原因是由于 llama_index create index 导致的错误，目前已升级 llama_index 到最新，修改了 from_documents 方法。还请测试一下重新拉取镜像是否可以成功，谢谢🙏

**Comment by zarswow** [comment]
![image](https://user-images.githubusercontent.com/103822120/230638865-4229ad87-6979-41de-afc5-256bffbdadc0.png)
太棒了，成功了！感谢大佬的无私分享！

另外刚才不知道怎么用 GitHub 的桌面客户端，乱点好像把这个仓库给分支到我的仓库里面去了，希望没造成什么不好的影响。。。我给它删掉了
