### ISSUE TITLE
OpenAI API Key Required & Error fetching models.

### ISSUE THREAD

**Issue by thisisowenlo** [guangzhengli/ChatFiles#16]
在本地端分別運行  chatfiles-ui 與 chatfiles
已經在 /chatfiles 下建好 .env，並設定 OPENAI_API_KEY=XXXXX
但運行起來後又方文字提示 OpenAI API Key Required
到左下角將 Key 輸入後仍顯示 

Error fetching models.
Make sure your OpenAI API key is set in the bottom left of the sidebar.
If you completed this step, OpenAI may be experiencing issues.

**Comment by thisisowenlo** [comment]
本地端報錯的訊息：

ready - started server on 0.0.0.0:3005, url: http://localhost:3005
event - compiled client and server successfully in 2s (229 modules)
wait  - compiling...
event - compiled successfully in 384 ms (192 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2.7s (5492 modules)
wait  - compiling /api/models (client and server)...
event - compiled successfully in 403 ms (43 modules)
wait  - compiling /_error (client and server)...
error - Class extends value undefined is not a constructor or null

This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/file.js (evalmachine.<anonymous>:5724:19)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/formdata.js (evalmachine.<anonymous>:5881:49)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/body.js (evalmachine.<anonymous>:6094:35)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/response.js (evalmachine.<anonymous>:6510:49)
    at __require (evalmachine.<anonymous>:14:50)
    at <unknown> (evalmachine.<anonymous>:11635:30)
    at requireFn (file:///Users/owenytlo/Documents/ChatFiles/chatfiles-ui/node_modules/next/dist/compiled/edge-runtime/index.js:1:7079) {
  name: 'TypeError'
}

**Comment by licesun** [comment]
如果你在某些不能顺利访问openAI 的地区，请设置全局代理。

**Comment by Samuel0807** [comment]
我也是本地运行会这样，docker运行正常

**Comment by lidedongsn** [comment]
chatfiles     | Token indices sequence length is longer than the specified maximum sequence length for this model (1439 > 1024). Running this sequence through the model will result in indexing errors
chatfiles-ui  |  [TypeError: fetch failed] {
chatfiles-ui  |   cause:  [ConnectTimeoutError: Connect Timeout Error] {
chatfiles-ui  |   name: 'ConnectTimeoutError',
chatfiles-ui  |   code: 'UND_ERR_CONNECT_TIMEOUT',
chatfiles-ui  |   message: 'Connect Timeout Error'
chatfiles-ui  | }
chatfiles-ui  | }

**Comment by tpeaua** [comment]
I'm getting this error, I first had a key but got the error then I changed the key and still the same.  I've added the new key to the bottom left hand corner for api keys of the localhost:3000 .  I've updated the new key on the .yml and .env files.  thanks again.

**Comment by funnymadpia** [comment]
我这里也抛出了同样的错误，我在centos7中使用docker 组合启动，并输入完api-key之后，出现了这样的结果
![model-error](https://user-images.githubusercontent.com/114943644/233770879-bbcfbede-2b9b-42c7-bf7c-390c1f4c03a9.png)
我发现它请求的位置是ui运行的端口，也不是python对应的后端端口
![request-por-error](https://user-images.githubusercontent.com/114943644/233770901-f5eab804-b528-45fe-9a01-6726a9b562fa.png)

因此，我比较怀疑是否对应这里的前端请求接口出现了问题，我查看network其请求的接口时找到了对应的代码
![image](https://user-images.githubusercontent.com/114943644/233770929-e955f70f-f33b-45f8-a67f-6807fd2d5754.png)

**Comment by qq-22841387** [comment]
我这里遇到了相同的问题，在centos7的台式机上通过docker compose运行，输入完api-key后，在请求model时遇到了这样的问题
![model-error](https://user-images.githubusercontent.com/100123156/233771040-25ff31e8-d14f-4912-860f-1bb0a55edeb6.png)
通过浏览器查看network请求位置时，发现这个请求的路径时3000（前端运行的端口）
![request-por-error](https://user-images.githubusercontent.com/100123156/233771109-86a5f135-22fb-43f0-837a-ee2bcdd9b277.png)

> 我不太清楚这里的核心运行逻辑，但是我发现后端运行的端口应该默认是5000
![image](https://user-images.githubusercontent.com/100123156/233771086-e6a7c6cd-4d56-4a0b-875e-9d5cb04471b7.png)

再次刷新页面后，出错的警告是在前端中
![image](https://user-images.githubusercontent.com/100123156/233771149-14007c10-c293-4e42-b186-6e60f35273c5.png)

都是相同的请求超时问题，我不太清楚这个是否和我的操作或配置有关，所以希望可以得到一个解决方案，谢谢

**Comment by liugddx** [comment]
I have the same problem, what is the solution?

**Comment by tpeaua** [comment]
I installed on Digital Ocean droplet using Fedora, it worked perfectly using the same AI keys.  I was trying to run it on macOS Catalina, not sure if its my version of OS and plus I'm just running pure CPU and not GPU.  I

**Comment by Chenhuaqi6** [comment]
请问有解决吗?我也是同样的问题

**Comment by ZimaBlueee** [comment]
i hava the same problem on ubuntu 22.04, please help out

**Comment by Faintabc** [comment]
same problem

**Comment by guangzhengli** [comment]
Hi everyone, ChatFiles has been refactored with Langchain and now fix this issue. #81
