### ISSUE TITLE
Can it support multiple OPENAIs_ API_ Load balancing between KEY

### ISSUE THREAD

**Issue by aapelismith** [guangzhengli/ChatFiles#2]
Can it support multiple OPENAIs_ API_ Load balancing between KEY? 
能否支持在多个 OPENAI_API_KEY 之间负载均衡?

**Comment by BooniesFX** [comment]
本地运行，其他的GPT client可以用，但是ChatFile一直报无法获得models

**Comment by pingyaowahao** [comment]
> 本地运行，其他的GPT client可以用，但是ChatFile一直报无法获得models

我也遇到同样的问题 Error fetching models.

**Comment by guangzhengli** [comment]
@BooniesFX  @pingyaowahao 请问有输入 OpenAPI token 到 .env 文件，然后启动 docker-compose 吗？我目前暂时无法复现这个问题。

**Comment by guangzhengli** [comment]
@aapelismith 可能暂时没有这个计划，目前优先级还是提高对话的效果和功能增强。

**Comment by BooniesFX** [comment]
@guangzhengli local run, OpenAPI token 也加到 .env 文件里，似乎无效果，然后在页面上又添加了还是Error fetching models的问题

**Comment by dimsky** [comment]
`const response = await fetch('/api/models', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        key,
      }),
    });`
同样的错误，发现是这个请求报错，在代码中没有发现此请求的路由或者接口定义。

**Comment by guangzhengli** [comment]
@BooniesFX @dimsky 因为这个接口是预留给 GPT-4 用的，目前 llama_index 只用 GPT-3.5 暂时没用 fetch models。请问是上传文件的时候报错了吗？还是打开页面就报错了？

**Comment by BooniesFX** [comment]
@guangzhengli 上传文件的时候报错

**Comment by dimsky** [comment]
> @BooniesFX @dimsky 因为这个接口是预留给 GPT-4 用的，目前 llama_index 只用 GPT-3.5 暂时没用 fetch models。请问是上传文件的时候报错了吗？还是打开页面就报错了？

了解，我猜可能是因为 next.js api 中的 fetch 请求貌似不支持默认的系统代理导致的。
我这边设置了 http_proxy，但是fetch默认没走系统网络代理，我猜很多同学都是这个问题。

**Comment by pingyaowahao** [comment]
打开页面几秒钟后自动报错，还没有上传文件
________________________________
发件人: guangzhengli ***@***.***>
发送时间: 2023年4月6日 23:25
收件人: guangzhengli/ChatFiles ***@***.***>
抄送: pingyaowahao ***@***.***>; Mention ***@***.***>
主题: Re: [guangzhengli/ChatFiles] Can it support multiple OPENAIs_ API_ Load balancing between KEY (Issue #2)


@BooniesFX<https://github.com/BooniesFX> @dimsky<https://github.com/dimsky> 因为这个接口是预留给 GPT-4 用的，目前 llama_index 只用 GPT-3.5 暂时没用 fetch models。请问是上传文件的时候报错了吗？还是打开页面就报错了？

―

**Comment by KyoMio** [comment]
我用软路由开的透明代理，没有设置本地的系统代理，也遇到了这个问题，Error fetching models。

**Comment by guangzhengli** [comment]
Hello everyone, ChatFiles has been refactored with Langchain and now fix this issue. #81
