### ISSUE TITLE
怎么改语言，现在是英文的，我投喂的资料是中文的

### ISSUE THREAD

**Issue by yuexiadudiao** [guangzhengli/ChatFiles#24]

**Comment by zdy85730** [comment]
直接告诉gpt用中文回答

**Comment by yuexiadudiao** [comment]
> promts要修改一下，程序里的promts有歧义

改了一下，体验还是不好，本地搜索不到就直接摆烂了

**Comment by rdaim** [comment]
同问，设置为zh语言，但是没有效果，我也配置了zh 下面的 common

**Comment by hycao** [comment]
在提示语最后回答添加 `IN CHINESE` 试试:
```
DEFAULT_PROMPT = (
    "We have provided context information below: \n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "Given this information, Please answer my question in the same language that I used to ask you.\n"
    "Please answer the question in chinese: {query_str}\n"
)
```

**Comment by hycao** [comment]
> > 在提示语最后回答添加 `IN CHINESE` 试试:
> > ```
> > DEFAULT_PROMPT = (
> >     "We have provided context information below: \n"
> >     "---------------------\n"
> >     "{context_str}\n"
> >     "---------------------\n"
> >     "Given this information, Please answer my question in the same language that I used to ask you.\n"
> >     "Please answer the question in chinese: {query_str}\n"
> > )
> > ```
> 
> 没用啊

能描述的更清楚吗，我这边虽然没继续用这个东西，但是之前一直用的很正常
