### ISSUE TITLE
设置的代理域名，但访问报错。

### ISSUE THREAD

**Issue by yhwymy** [guangzhengli/ChatFiles#26]
已经在文件中设置了代理域名，docker中启动为什么访问还会报错呢？本地启动就没问题。很是奇怪。
export const OPENAI_API_HOST =
  process.env.OPENAI_API_HOST || 'balabala.xyz';

**Comment by yhwymy** [comment]
项目跟路径上的 .env 文件里也放了OPENAI_API_KEY='sk-sr6u6eceP1okuZa30gQQT3BlbkF'

**Comment by hycao** [comment]
我在 `llm.py` 文件中

```
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
openai.api_key = OPENAI_API_KEY
## 添加了如下代码就设置了代理域名
openai.api_base = "https://XXX.XX/v1"
```
你可以试试
另外，在 ISSUE 中暴漏 key 是一件很危险的事情
