### ISSUE TITLE
 docker-compose up error

### ISSUE THREAD

**Issue by JoyceLiC** [guangzhengli/ChatFiles#3]
chatfiles       | standard_init_linux.go:211: exec user process caused "exec format error"
chatfiles-ui    | standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by ezreal130** [comment]
[root@future ChatFiles]# docker compose up
[+] Running 2/0
 ⠿ Container chatfiles     Created                                                                                                                             0.0s
 ⠿ Container chatfiles-ui  Created                                                                                                                             0.0s
Attaching to chatfiles, chatfiles-ui
chatfiles     | exec /usr/local/bin/python3: exec format error
chatfiles exited with code 1
chatfiles-ui  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
chatfiles-ui exited with code 1

**Comment by guangzhengli** [comment]
Can you provide your operating system and architecture? arm or x64?

**Comment by liugddx** [comment]
> Can you provide your operating system and architecture? arm or x64?
I have the same problem.This is the information of my system

Linux VM-4-17-centos 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by guangzhengli** [comment]
This error should be caused by me only packaging the arm64 docker image. Currently, I have pushed both amd64 and arm64 images. You can delete the local image and download it again.
