### ISSUE TITLE
请问可以支持流失输出吗？一个字一个字蹦出来那种

### ISSUE THREAD

**Issue by kuangkung** [guangzhengli/ChatFiles#31]
如题，另外想知道「上传多个文件，构建同一个 Index，然后与之对话。」这个feature大概什么时候能好，或者说告诉下我实现原理，我自己试试看，多谢~

**Comment by kuangkung** [comment]
还有一个，如何让它能默认输出中文呀

**Comment by LS13157af** [comment]
把每个文件都切块然后保存到同一个index就行了，用pinecone实现是最快捷的

**Comment by guangzhengli** [comment]
The priority of this requirement is not high, but we will consider introducing this feature if there is an opportunity. 
Different embedding indexes are organized through building graphs. This feature has already been implemented. #43 #44
