### ISSUE TITLE
我在本地运行程序的时候，会提示没有安装“pytorch或者TensorFlow”

### ISSUE THREAD

**Issue by maxweber36** [guangzhengli/ChatFiles#34]
我在dockerfiles已经添加了安装pytorch和TensorFlow的指令。
<img width="934" alt="image" src="https://user-images.githubusercontent.com/12783025/232173794-f862de1f-2ae2-4a2b-a90c-ac18072230d8.png">

但是在运行docker镜像的时候，依然会提示"没有构建“pytorch或者TensorFlow”的信息。
<img width="570" alt="image" src="https://user-images.githubusercontent.com/12783025/232173969-dfc324d8-a1d4-470b-bc48-f07c876c15b6.png">

**Comment by guangzhengli** [comment]
Ignore it, this will not affect the use.
