### ISSUE TITLE
Issue uploading the file

### ISSUE THREAD

**Issue by xubairp** [guangzhengli/ChatFiles#39]
hi,
 i tried to upload the PDF file, while there was no error during the upload process, however after the process is done, instead of showing name of the file on top, it shows some unparsed html code. please check the attached images:

![image](https://user-images.githubusercontent.com/128311411/232263837-dcf75bc9-3b7f-4569-b078-b40cb846e7f0.png)

![image](https://user-images.githubusercontent.com/128311411/232263856-c0534b56-130f-4400-a49f-a2f41afe0b01.png)

**Comment by xubairp** [comment]
I tried again and this time with shorter pdf file name "iso.pdf" and still having same issue. please check the image :

![image](https://user-images.githubusercontent.com/128311411/232562934-c360d4f3-cae9-4072-87c0-47c53fce69eb.png)


but if try to chat without the attachment, it works fine by sending and receiving the response from the openai api.

![image](https://user-images.githubusercontent.com/128311411/232563403-9b312b22-2623-4417-92a9-84410da9582c.png)

**Comment by xubairp** [comment]
Above issue is resolved, i noticed the python was nothing running in the backend. however, now i face another error when i upload any file:

![image](https://user-images.githubusercontent.com/128311411/233773211-c1cdd55d-f22c-4d10-8ae5-3d1756735cca.png)

**Comment by hjaiim** [comment]
I have the same problem. How did you solve it

**Comment by hjaiim** [comment]
> Above issue is resolved, i noticed the python was nothing running in the backend. however, now i face another error when i upload any file:
> 
> ![image](https://user-images.githubusercontent.com/128311411/233773211-c1cdd55d-f22c-4d10-8ae5-3d1756735cca.png)

I have the same problem. How did you solve it

**Comment by guangzhengli** [comment]
Hello everyone, ChatFiles has been refactored with Langchain and fixed this issue. #81
