### ISSUE TITLE
上传pdf或epub文件时，提示错误

### ISSUE THREAD

**Issue by w0017** [guangzhengli/ChatFiles#42]
上传pdf或epub文件时，页面提示如下：错误
Error
Unexpected token '<', "<html> <h"... is not valid JSON.
[《斯坦福高效睡眠法》.pdf](https://github.com/guangzhengli/ChatFiles/files/11248290/default.pdf)

**Comment by w0017** [comment]
我用nginx做了转发，对外暴露的是https接口

**Comment by guangzhengli** [comment]
Can you provide more detail about this issue, or is the  same issue like #36

**Comment by wangfeng35** [comment]
> Can you provide more detail about this issue, or is the same issue like #36

本地搭建对电脑性能有要求么？ 我试了下好像一瞬间就挂了。

你提供的网页demo版能自己输入api_key后增加上传文件大小么？

**Comment by guangzhengli** [comment]
> > Can you provide more detail about this issue, or is the same issue like #36
> 
> 本地搭建对电脑性能有要求么？ 我试了下好像一瞬间就挂了。
> 
> 你提供的网页demo版能自己输入api_key后增加上传文件大小么？

对本地性能没有要求，对本地的网络有要求。因为 embedding 的操作主要在后端，输入 api_key 意味着把 key 交给我，虽然我不会拿来用，但是为了安全起见还是自己保管吧。目前网页demo版用的是我个人的 key，免费额度被 OpenAI 限制的比较严重，但我也没有办法做到更多了。
