### ISSUE TITLE
请问该项目可以使用除了ChatGPT之外的其他开源大语言模型吗？

### ISSUE THREAD

**Issue by fishfree** [guangzhengli/ChatFiles#46]
我看本项目用了LlamaIndex和langchain，我看简介好像是这两个项目或库能调用其他的开源大语言模型，但我是小白、不确定，详情大神确认一下。
如果是的， 该怎么修改代码呢？非常感谢！

**Comment by guangzhengli** [comment]
Currently, other embedding models are not supported and will be modified or maintained according to the choices of the open-source community in the future.

You can replace the embedding models in chatfiles folder llm.py
