### ISSUE TITLE
docker本地运行，请求都500？有遇到的吗

### ISSUE THREAD

**Issue by yj666** [guangzhengli/ChatFiles#48]
![image](https://user-images.githubusercontent.com/26574779/233029892-8cf8670e-bdd0-49aa-bdd5-3d04cf9a8d54.png)

**Comment by guangzhengli** [comment]
it is a duplicate issue with #16

**Comment by tpeaua** [comment]
I did clean install on my DigitalOcean droplet free trial and it works perfect.  Seems like my local install on my 2011 macOS Catalina was slow and out of date.  I have it running on Fedora and its running like a charm.  thanks again and great stuff!!!!!!!!!
