### ISSUE TITLE
i18n Multilingual Support

### ISSUE THREAD

**Issue by rdaim** [guangzhengli/ChatFiles#50]
设置为zh语言，但是没有效果，我也配置了zh 下面的 common

**Comment by guangzhengli** [comment]
I have currently added support for Chinese. You can access it through the `/zh` path like `http://localhost:3000/zh`, but there are still some parts that haven't been fully fixed and are not in Chinese. If anyone is interested, you can fix it.

**Comment by rdaim** [comment]
非常感谢！！！

**Comment by ivan-vilches** [comment]
howe i can get answers on spanish?

**Comment by guangzhengli** [comment]
You can add support for the Spanish language under public/locales.
