### ISSUE TITLE
Can't drag and drop

### ISSUE THREAD

**Issue by soongin** [guangzhengli/ChatFiles#52]
drag and drop is not working on demo and locally deployed instance.

**Comment by guangzhengli** [comment]
Can you open Chrome dev tools and get the response status when sending `/upload` request? or provider some container logs?

**Comment by soongin** [comment]
> Can you open Chrome dev tools and get the response status when sending `/upload` request? or provider some container logs?

I can't catch log because it just open in new tab from chrome. edge.
I captured screen and share it https://imgur.com/a/2UGJ50E

Thanks.

**Comment by guangzhengli** [comment]
Currently, the entire project has been refactored using Langchain and this issue has been resolved. #81
