### ISSUE TITLE
几点产品上的建议

### ISSUE THREAD

**Issue by rdaim** [guangzhengli/ChatFiles#56]
可以支持多用户
可以支持已有文件索引列表的展示及管理
可以支持远程文件的读取分析，输入URL即可，这个其实很容易的
支持token统计及openAI详细的错误露出，以方便调试。

**Comment by rdaim** [comment]
总体上来说，这个产品原型是非常棒的，感谢作者的辛苦付出，手工赞！！！

**Comment by huawuhen** [comment]
最主要不支持访问认证，这样很容易别陌生人使用耗尽额度
