### ISSUE TITLE
Error: RetryError[<Future at 0x7f19db1d9400 state=finished raised RateLimitError>]

### ISSUE THREAD

**Issue by rdaim** [guangzhengli/ChatFiles#57]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/38274819/233662075-3e3565da-8df6-4445-a6f0-224b79a48e46.png">

**Comment by QinghangPeng** [comment]
"RateLimitError"是指调用API时超出了API提供商设定的访问速率限制。尝试本地部署项目，并使用自己的open api key来体验功能
