### ISSUE TITLE
Support Azure OpenAI API

### ISSUE THREAD

**Issue by kotobuki09** [guangzhengli/ChatFiles#6]
Could you make it support Azure OpenAI API?

**Comment by guangzhengli** [comment]
Perhaps there is no plan for this at the moment, and we may consider adding Azure OpenAPI key after the stability of subsequent functions. Currently, our priority is to improve the effectiveness of conversations and enhance functionality.

**Comment by suikaremilia** [comment]
Is it possible to support custom openai_url? In this way, access to Azure openai can be realized through other projects.
There are many proxy projects from Azure openai api to openai on GitHub.

**Comment by licesun** [comment]
Sure， you can change the openai_url  in  chatfiles-ui/utils/app/const.ts.

**Comment by zhuyaguang** [comment]
> Sure， you can change the openai_url in chatfiles-ui/utils/app/const.ts.

In Azure , change OPENAI_API_HOST to Azure endpoint ?

**Comment by suikaremilia** [comment]
It's not that simple, the authentication methods of azure api and openai api are different. 
But there are many projects on github that convert Azure api to openai api. Through these projects, the azure api can be converted to the same as that of openai, except that the endpoint is different.
In theory, after this conversion, you can use Azure api in this project, but I feel that only changing the front end is not enough.

I am also trying, it is best to define the endpoint as an independent variable.

**Comment by wktdwktd** [comment]
我尝试使用代理，用的这个项目https://github.com/stulzq/azure-openai-proxy

但是没有成功，有没有大佬已经实现，我想使用azure的key

**Comment by guangzhengli** [comment]
Hello everyone, ChatFiles has been refactored with Langchain and now supports Azure OpenAI Service. #81
