### ISSUE TITLE
请问在前端出现这个报错是什么原因

### ISSUE THREAD

**Issue by hq0709** [guangzhengli/ChatFiles#61]
感谢您优秀的项目！
Unexpected token '<', "<!DOCTYPE "... is not valid JSON.
在上传文件后，在前端出现这个错误，不知道如何解决

**Comment by hq0709** [comment]
还有请问如何解除文件大小的限制

**Comment by longxiaotian799** [comment]
我也是这个问题

**Comment by hq0709** [comment]
已解决报错，在const.ts文件中修改端口号为server运行的端口

**Comment by guangzhengli** [comment]
Currently, the entire project has been refactored using Langchain and this issue has been resolved. #81
