### ISSUE TITLE
可以添加自定义 API 请求地址吗？

### ISSUE THREAD

**Issue by easychen** [guangzhengli/ChatFiles#68]
因为某些原因国内无法直接访问 OpenAI API，如果能添加 自定义 API 请求地址，就可以使用如 [API2D](https://api2d.com) 这样的中转服务了。

我尝试在 docker-composer 和 server.py 加了下参数，但似乎不生效 😶

<img width="521" alt="image" src="https://user-images.githubusercontent.com/1294760/236382585-0fbedfee-02c9-4735-a344-96d889961676.png">

<img width="448" alt="image" src="https://user-images.githubusercontent.com/1294760/236382563-aebb889b-5a1a-4b7d-af69-21e9d3e1df31.png">

**Comment by ZimaBlueee** [comment]
你好，请问解决了吗
