### ISSUE TITLE
请问前端这个接口如何设置代理呢?

### ISSUE THREAD

**Issue by Chenhuaqi6** [guangzhengli/ChatFiles#73]
![image](https://github.com/guangzhengli/ChatFiles/assets/43661509/612c38b5-c562-412a-a6cf-091891bb5e59)

<img width="701" alt="image" src="https://github.com/guangzhengli/ChatFiles/assets/43661509/3d504fe5-1055-44e1-b824-26a9c38557f6">

**Comment by ZimaBlueee** [comment]
> ![image](https://user-images.githubusercontent.com/43661509/241115844-612c38b5-c562-412a-a6cf-091891bb5e59.png)
> 
> <img alt="image" width="701" src="https://user-images.githubusercontent.com/43661509/241115893-3d504fe5-1055-44e1-b824-26a9c38557f6.png">

请问解决了吗？

**Comment by guangzhengli** [comment]
Currently, the entire project has been refactored using Langchain and this issue has been resolved. #81
