### ISSUE TITLE
v1/chat/completions 这个接口出错了

### ISSUE THREAD

**Issue by ge1124683115** [guangzhengli/ChatFiles#74]
前端时间还是好的，今天发现这个接口突然报错了，不知道是不是openAi检测到了这个是在国内使用的问题，但是我们的服务器是部署在国外的。
![image](https://github.com/guangzhengli/ChatFiles/assets/32546124/1e9a38c6-4200-45a1-a2b1-68a97233b271)
![image](https://github.com/guangzhengli/ChatFiles/assets/32546124/6d7614cf-d916-4581-9646-82c90da101b3)
并且models接口是正常的
![image](https://github.com/guangzhengli/ChatFiles/assets/32546124/05743aff-f8d7-4890-a2df-e5e2406799bb)

**Comment by ge1124683115** [comment]
![image](https://github.com/guangzhengli/ChatFiles/assets/32546124/af6d90d5-62dc-4379-8962-1654af285838)

**Comment by guangzhengli** [comment]
Currently, the entire project has been refactored using Langchain and this issue has been resolved. #81
