### ISSUE TITLE
Got unexpected answer

### ISSUE THREAD

**Issue by rakshitsharma574** [guangzhengli/ChatFiles#79]
when i uploaded my pdf file and ask some question it give me response like this -  "The original answer is still accurate and does not need to be refined." i got these type of response many times with my question and some time it give answer. 
i am using only python backend and testing API in postman and in response sometime i got correct answer and sometime i got the above mention answer

**Comment by guangzhengli** [comment]
Currently, the entire project has been refactored using Langchain and this issue has been resolved. #81
