### ISSUE TITLE
作者您好，请问可以更新LangChain的中文部署文档吗？

### ISSUE THREAD

**Issue by ZimaBlueee** [guangzhengli/ChatFiles#82]
我非常喜欢您的项目，太有创意了，我一直觉得本地知识库才是未来，希望可以完善LangChain的中文文档，辛苦了！

顺便问一下，请问本地模型对中文的支持咋样呀？

**Comment by guangzhengli** [comment]
you can deploy to Vercel by clicking the deploy button now. I will add zh doc soon...
