### ISSUE TITLE
cant upload PDF

### ISSUE THREAD

**Issue by Huayu-Qin** [guangzhengli/ChatFiles#85]
Cant upload pdf, shows that ```API resolved without sending a response for /api/files?fileName=deb691a6-b77e-43f4-b057-d96f52a4706f.pdf, this may result in stalled requests.```
<img width="1138" alt="Screenshot 2023-06-16 at 10 09 37" src="https://github.com/guangzhengli/ChatFiles/assets/69624699/28ca1c30-af7e-4fed-9ca3-f09e928a1af4">
<img width="1000" alt="Screenshot 2023-06-16 at 10 13 09" src="https://github.com/guangzhengli/ChatFiles/assets/69624699/92e73ecf-3784-4b86-bd95-c434c1b82a39">
How should I do to handle it? Thanks.

**Comment by Huayu-Qin** [comment]
> > > How did you solve this problem?
> > 
> > 
> > `NEXT_PUBLIC_CHAT_FILES_UPLOAD_PATH=public/uploads` define the path of document saved, and you should build that directory in the public folder like `/public/uploads`
> 
> Thanks, no more errors now. But still unable to upload the file, it has been uploading, the request: `api/embedding` has not responded for tens of minutes, and no error has been reported. I don’t know why



> Remember

What embedding model API do you use? I tried the API of llm and the embedding model from Openai and it works.

**Comment by ZimaBlueee** [comment]
> > > > How did you solve this problem?
> > > 
> > > 
> > > `NEXT_PUBLIC_CHAT_FILES_UPLOAD_PATH=public/uploads` define the path of document saved, and you should build that directory in the public folder like `/public/uploads`
> > 
> > 
> > Thanks, no more errors now. But still unable to upload the file, it has been uploading, the request: `api/embedding` has not responded for tens of minutes, and no error has been reported. I don’t know why
> 
> > Remember
> 
> What embedding model API do you use? I tried the API of llm and the embedding model from Openai and it works.

I also use the key of openai 3.5. I deployed it on ubuntu according to the readme, but the request has been blocked.

**Comment by Huayu-Qin** [comment]
> > > > > How did you solve this problem?
> > > > 
> > > > 
> > > > `NEXT_PUBLIC_CHAT_FILES_UPLOAD_PATH=public/uploads` define the path of document saved, and you should build that directory in the public folder like `/public/uploads`
> > > 
> > > 
> > > Thanks, no more errors now. But still unable to upload the file, it has been uploading, the request: `api/embedding` has not responded for tens of minutes, and no error has been reported. I don’t know why
> > 
> > 
> > > Remember
> > 
> > 
> > What embedding model API do you use? I tried the API of llm and the embedding model from Openai and it works.
> 
> I also use the key of openai 3.5. I deployed it on ubuntu according to the readme, but the request has been blocked.

Sorry, I haven't tried to deploy it on ubuntu and you might need to ask a new question about it and others who figure it out could help you.

**Comment by ZimaBlueee** [comment]
> > > > > > How did you solve this problem?
> > > > > 
> > > > > 
> > > > > `NEXT_PUBLIC_CHAT_FILES_UPLOAD_PATH=public/uploads` define the path of document saved, and you should build that directory in the public folder like `/public/uploads`
> > > > 
> > > > 
> > > > Thanks, no more errors now. But still unable to upload the file, it has been uploading, the request: `api/embedding` has not responded for tens of minutes, and no error has been reported. I don’t know why
> > > 
> > > 
> > > > Remember
> > > 
> > > 
> > > What embedding model API do you use? I tried the API of llm and the embedding model from Openai and it works.
> > 
> > 
> > I also use the key of openai 3.5. I deployed it on ubuntu according to the readme, but the request has been blocked.
> 
> Sorry, I haven't tried to deploy it on ubuntu and you might need to ask a new question about it and others who figure it out could help you.

What platform are you deploying on?Thanks！

**Comment by Huayu-Qin** [comment]
> > > > > > > How did you solve this problem?
> > > > > > 
> > > > > > 
> > > > > > `NEXT_PUBLIC_CHAT_FILES_UPLOAD_PATH=public/uploads` define the path of document saved, and you should build that directory in the public folder like `/public/uploads`
> > > > > 
> > > > > 
> > > > > Thanks, no more errors now. But still unable to upload the file, it has been uploading, the request: `api/embedding` has not responded for tens of minutes, and no error has been reported. I don’t know why
> > > > 
> > > > 
> > > > > Remember
> > > > 
> > > > 
> > > > What embedding model API do you use? I tried the API of llm and the embedding model from Openai and it works.
> > > 
> > > 
> > > I also use the key of openai 3.5. I deployed it on ubuntu according to the readme, but the request has been blocked.
> > 
> > 
> > Sorry, I haven't tried to deploy it on ubuntu and you might need to ask a new question about it and others who figure it out could help you.
> 
> What platform are you deploying on?Thanks！

I only tested the functionality on the local deployment.

**Comment by ZimaBlueee** [comment]
Is it a Windows platform?Thanks

**Comment by Huayu-Qin** [comment]
> Is it a Windows platform?Thanks

no I deployed it on Mac but I access the openai with no proxy.

**Comment by ZimaBlueee** [comment]
> > Is it a Windows platform?Thanks
> 
> no I deployed it on Mac but I access the openai with no proxy.

Got it, thank you!

**Comment by vipulchaube** [comment]
> Cant upload pdf, shows that `API resolved without sending a response for /api/files?fileName=deb691a6-b77e-43f4-b057-d96f52a4706f.pdf, this may result in stalled requests.` <img alt="Screenshot 2023-06-16 at 10 09 37" width="1138" src="https://user-images.githubusercontent.com/69624699/246373025-28ca1c30-af7e-4fed-9ca3-f09e928a1af4.png"> <img alt="Screenshot 2023-06-16 at 10 13 09" width="1000" src="https://user-images.githubusercontent.com/69624699/246373180-92e73ecf-3784-4b86-bd95-c434c1b82a39.png"> How should I do to handle it? Thanks.

i have tried making a folder in the root directory in public called uploads. I have changed the path to NEXT_PUBLIC_CHAT_FILES_UPLOAD_PATH=public/uploads.. i have also tried backslashes as i am using windows. But still not able to upload a file 
![Screenshot (116)](https://github.com/guangzhengli/ChatFiles/assets/58715392/fad51289-ec36-4d0a-b862-69e09d71ed96)
This is my console log. Help
