### ISSUE TITLE
save file error

### ISSUE THREAD

**Issue by ongkokl** [guangzhengli/ChatFiles#86]
hi

got this error on my deployed app 

![image](https://github.com/guangzhengli/ChatFiles/assets/50367330/78a64dec-eb27-4a15-8f1c-1149077f8a8a)

**Comment by ongkokl** [comment]
> hi have you checked your directory of the project? like this [#85 (comment)](https://github.com/guangzhengli/ChatFiles/issues/85#issue-1760243625)
i did but same error 
![image](https://github.com/guangzhengli/ChatFiles/assets/50367330/a92c80d8-cbf0-4b9c-ae58-446798ab2af0)

**Comment by guangzhengli** [comment]
If you want to deploy to Vercel, please set the path to /tmp, It is caused by the Vercel limit.

https://github.com/vercel/vercel/discussions/5320

**Comment by ongkokl** [comment]
> If you want to deploy to Vercel, please set the path to /tmp, It is caused by the Vercel limit.
> 
> [vercel/vercel#5320](https://github.com/vercel/vercel/discussions/5320)

Thanks, but now got this error

![image](https://github.com/guangzhengli/ChatFiles/assets/50367330/5611cd66-e532-4014-aa14-6d80b52d65f4)

**Comment by guangzhengli** [comment]
Can you provide more detailed logs found in Vercel logs after you upload the file?

**Comment by ongkokl** [comment]
> Can you provide more detailed logs found in Vercel logs after you upload the file?

hI

![image](https://github.com/guangzhengli/ChatFiles/assets/50367330/e2c384c4-e85a-4c47-907b-4eb40d51a7d3)

**Comment by guangzhengli** [comment]
This error message currently does not show a more detailed error stack.
