### ISSUE TITLE
environment variable not recognized

### ISSUE THREAD

**Issue by ZimaBlueee** [guangzhengli/ChatFiles#87]
![image](https://github.com/guangzhengli/ChatFiles/assets/53747502/12ad0628-c0b7-4500-a828-afcdec4dfc8d)

![image](https://github.com/guangzhengli/ChatFiles/assets/53747502/5a813b30-107b-421e-acfd-6c7c2b2563a0)

OS：ubuntu 22.04

As shown in the picture, I created the .env file in the root directory, and configured the key-value pairs of OPENAI_API_KEY and OPENAI_API_HOST, but these two parameters were not read after the project started, what should I do to make it take effect?

By the way, OPENAI_API_HOST is configured to go through the proxy, because it is impossible to directly request the openai official website

Looking forward to your reply

**Comment by guangzhengli** [comment]
Hii, you can follow the [env vars document](https://github.com/guangzhengli/ChatFiles/blob/main/doc/env-vars.md) to configure your env variables. If you want to use the OpenAI Key, you just need to set the OPENAI_TYPE=OPENAI and OPENAI_API_KEY.

However, unfortunately, ChatFiles currently does not support using proxy configuration like OPENAI_API_HOST.

**Comment by guangzhengli** [comment]
The solution to this issue may be help for you., https://github.com/hwchase17/langchainjs/issues/388
