### ISSUE TITLE
local run failed

### ISSUE THREAD

**Issue by shao-shuai** [guangzhengli/ChatFiles#9]
was trying to run the app locally, got this:
![image](https://user-images.githubusercontent.com/28980017/230515640-841b870b-030a-4a53-83e2-f688910d8461.png)

followed each step as specified:
`cd chatfiles-ui
npm install
npm run dev
cd chatfiles
python3 server.py`

my OS is Ubuntu 20.04

**Comment by licesun** [comment]
Check your python version , please.  3.8.2 above is required.

**Comment by licesun** [comment]
Check your node version

**Comment by shao-shuai** [comment]
> Check your node version

thanks for the reply, my node version is v19.8.1

**Comment by pithematic** [comment]
node v18.15.0 run correctly
