### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by irol765** [guangzhengli/ChatFiles#93]
Why is the interface in Chinese, but when I ask a question using Chinese, the answer is still in English and it seems like it doesn't support context.

**Comment by guangzhengli** [comment]
This may be because the default prompt is in English, which causes unstable responses in Chinese/English even if the uploaded text and question are in Chinese.

**Comment by irol765** [comment]
这个问题是否能在后续优化？

**Comment by guangzhengli** [comment]
This issue may be localized in the future, with different default prompts set according to different language settings. However, it is currently not a high priority.
